services:
  - type: web
    name: backend
    env: python
    pythonVersion: 3.10
    rootDir: backend   # your backend folder
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py